name: Maven Build and Deploy

on:
  push:
    branches:
      - main
    tags:
      - 'ALPHA-*'
      - 'BETA-*'
      - 'v*'

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Deploy with Maven
        if: startsWith(github.ref, 'refs/tags/')
        env:
          SETTINGS_XML: ${{ secrets.MAVEN_SETTINGS_XML }}
        run: |
          echo "$SETTINGS_XML" > settings.xml
          mvn --settings settings.xml deploy
